/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JFrame;
import javax.swing.*;
import java.awt.Color.*;
import java.awt.Image;
public class WindowApp extends JFrame {
    
    /**
     * Creates new form WindowApp
     */
    public WindowApp() {
        initComponents();
//        scaleImage(jLabel1);
    }
    
//    private void scaleImage( JLabel label){
//        ImageIcon icon = new ImageIcon(getClass().getResource("/Images/pictures/start-Poster.jpg"));
//        Image img = icon.getImage();
//        Image imgScale = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
//        ImageIcon scaledIcon = new ImageIcon(imgScale);
//        label.setIcon(scaledIcon);
//
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        header_PayOptions = new javax.swing.JPanel();
        head_PODesc = new javax.swing.JLabel();
        head_PODesc2 = new javax.swing.JLabel();
        Body = new javax.swing.JPanel();
        body_ImageCont = new javax.swing.JLabel();
        Footer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hello World");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(625, 800));

        panelMain.setBackground(new java.awt.Color(255, 255, 255));
        panelMain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelMain.setLayout(new java.awt.BorderLayout());

        Header.setPreferredSize(new java.awt.Dimension(100, 100));

        header_PayOptions.setBackground(new java.awt.Color(255, 184, 14));
        header_PayOptions.setBorder(javax.swing.BorderFactory.createEmptyBorder(10,10,10,10));
        header_PayOptions.setName(""); // NOI18N

        head_PODesc.setBackground(new java.awt.Color(255, 255, 255));
        head_PODesc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        head_PODesc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        head_PODesc.setText("Pay With Card or Cash");
        head_PODesc.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        head_PODesc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        head_PODesc.setOpaque(true);
        head_PODesc.setPreferredSize(new java.awt.Dimension(300, 16));

        head_PODesc2.setText("Gcash");

        javax.swing.GroupLayout header_PayOptionsLayout = new javax.swing.GroupLayout(header_PayOptions);
        header_PayOptions.setLayout(header_PayOptionsLayout);
        header_PayOptionsLayout.setHorizontalGroup(
            header_PayOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_PayOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(head_PODesc, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(head_PODesc2, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        header_PayOptionsLayout.setVerticalGroup(
            header_PayOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_PayOptionsLayout.createSequentialGroup()
                .addComponent(head_PODesc2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(header_PayOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(head_PODesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header_PayOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header_PayOptions, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelMain.add(Header, java.awt.BorderLayout.NORTH);

        Body.setLayout(new java.awt.BorderLayout());

        body_ImageCont.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        body_ImageCont.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pictures/start-Poster.jpg"))); // NOI18N
        body_ImageCont.setMaximumSize(new java.awt.Dimension(625, 500));
        body_ImageCont.setMinimumSize(new java.awt.Dimension(625, 500));
        Body.add(body_ImageCont, java.awt.BorderLayout.CENTER);

        panelMain.add(Body, java.awt.BorderLayout.CENTER);

        Footer.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout FooterLayout = new javax.swing.GroupLayout(Footer);
        Footer.setLayout(FooterLayout);
        FooterLayout.setHorizontalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 825, Short.MAX_VALUE)
        );
        FooterLayout.setVerticalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panelMain.add(Footer, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 1051, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body;
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel Header;
    public javax.swing.JLabel body_ImageCont;
    private javax.swing.JLabel head_PODesc;
    private javax.swing.JLabel head_PODesc2;
    private javax.swing.JPanel header_PayOptions;
    private javax.swing.JPanel panelMain;
    // End of variables declaration//GEN-END:variables
}
